Repository LiveSplit/livesplit-core, pull requests merged in 2020-04, with the labels that each got.

#322 Stop shrinking GIFs for now
  Cargo.toml
  src/settings/image/shrinking.rs
Labels: bug, enhancement

#323 Make Software Rendering `no_std` compatible
  Cargo.toml
  src/rendering/software/mod.rs
Labels: enhancement, feature, rendering

#327 Switch to checkout@v2
  .github/workflows/audit.yml
  .github/workflows/rust.yml
Labels: CI, code quality

#329 Run Tests on WASI
  .cargo/config
  .github/workflows/rust.yml
  .github/workflows/test.sh
  Cargo.toml
  src/rendering/software.rs
  src/tests_helper.rs
  tests/balanced_pb.rs
  tests/layout_files/mod.rs
  tests/layout_parsing.rs
  tests/rendering.rs
  tests/run_files/mod.rs
  tests/split_parsing.rs
Labels: CI, code quality, enhancement
