Repository LiveSplit/livesplit-core, pull requests merged in 2020-01, with the labels that each got.

#201 Implement Custom Variables
  capi/bind_gen/src/typescript.ts
  capi/src/lib.rs
  capi/src/run_editor.rs
  capi/src/run_metadata.rs
  capi/src/run_metadata_custom_variable.rs
  capi/src/run_metadata_custom_variables_iter.rs
  capi/src/run_metadata_speedrun_com_variable.rs
  capi/src/run_metadata_speedrun_com_variables_iter.rs
  capi/src/run_metadata_variable.rs
  capi/src/run_metadata_variables_iter.rs
  capi/src/text_component.rs
  capi/src/text_component_state.rs
  src/component/text/mod.rs
  src/component/text/tests.rs
  src/layout/component.rs
  src/platform/no_std/indexmap.rs
  src/rendering/component/text.rs
  src/rendering/software/mod.rs
  src/run/editor/mod.rs
  src/run/editor/tests/custom_variables.rs
  src/run/editor/tests/dissociate_run.rs
  src/run/editor/tests/mark_as_modified.rs
  src/run/editor/tests/mod.rs
  src/run/mod.rs
  src/run/parser/face_split.rs
  src/run/parser/livesplit.rs
  src/run/parser/splits_io.rs
  src/run/parser/splitterz.rs
  src/run/parser/worstrun.rs
  src/run/parser/wsplit.rs
  src/run/run_metadata.rs
  src/run/saver/livesplit.rs
  src/run/tests/metadata.rs
  src/timing/timer/mod.rs
  src/timing/timer/tests/mark_as_modified.rs
  src/timing/timer/tests/mod.rs
  src/timing/timer/tests/variables.rs
Labels: enhancement, feature

#288 Implement Segment Timer mode for Timer Component
  src/component/detailed_timer/mod.rs
  src/component/timer.rs
  src/timing/formatter/timer.rs
Labels: enhancement, feature

#294 Improve Annotations on CI
  .github/workflows/rust.yml
  capi/bind_gen/src/java/jna.rs
  capi/bind_gen/src/jni_cpp.rs
  capi/bind_gen/src/python.rs
  src/platform/no_std/indexmap.rs
  src/rendering/software/tests.rs
Labels: CI, code quality, enhancement

#295 Run Fixing Algorithms when opening splits
  src/run/editor/mod.rs
  src/run/editor/tests/mod.rs
  src/run/tests/fixing.rs
  src/timing/timer/mod.rs
Labels: bug, enhancement

#299 Remove emscripten
  .cargo/config
  .github/workflows/build_static.sh
  .github/workflows/rust.yml
  .gitignore
  Cargo.toml
  README.md
  capi/bind_gen/src/emscripten.rs
  capi/bind_gen/src/main.rs
  capi/js/Cargo.toml
  capi/js/Makefile
  capi/js/node/package.json
  capi/js/package-lock.json
  capi/js/package.json
  capi/js/src/main.rs
  capi/js/tsconfig.json
  capi/src/lib.rs
  crates/livesplit-hotkey/Cargo.toml
  crates/livesplit-hotkey/src/emscripten/key_code.rs
  crates/livesplit-hotkey/src/emscripten/mod.rs
  crates/livesplit-hotkey/src/lib.rs
  src/hotkey_config.rs
  src/platform/mod.rs
Labels: CI, code quality

#290 capi: Make some minor fixes
  capi/src/hotkey_config.rs
  capi/src/key_value_component_state.rs
  capi/src/splits_component_state.rs
Labels: c api, enhancement

#289 capi: Expose Layout State object
  capi/src/layout.rs
  capi/src/layout_state.rs
  capi/src/lib.rs
  capi/src/separator_component.rs
  capi/src/separator_component_state.rs
Labels: c api, enhancement
