Repository LiveSplit/livesplit-core, pull requests merged in 2023-02, with the labels that each got.

#631 Update various dependencies and fix a bug
  .github/workflows/build.yml
  .github/workflows/test.sh
  Cargo.toml
  README.md
  crates/livesplit-auto-splitting/Cargo.toml
  src/run/mod.rs
Labels: bug, enhancement, dependencies, rendering, feature, ci

#632 Download a prebuilt version of cross in CI
  .github/workflows/build.yml
Labels: enhancement, ci

#634 livesplit-hotkey: Make `Hook` Send + Sync
  crates/livesplit-hotkey/Cargo.toml
  crates/livesplit-hotkey/src/lib.rs
  crates/livesplit-hotkey/src/linux/evdev_impl.rs
  crates/livesplit-hotkey/src/linux/mod.rs
  crates/livesplit-hotkey/src/linux/x11_impl.rs
  crates/livesplit-hotkey/src/macos/mod.rs
Labels: bug, enhancement, code quality, hotkey
